version: '2'
services:
  wiki:
    build: .
    environment:
      MEDIAWIKI_HTTPS: 1
      MEDIAWIKI_SERVER: https://localhost
      MEDIAWIKI_SITENAME: MyWiki
      MEDIAWIKI_LANGUAGE_CODE: en
      MEDIAWIKI_SECRET_KEY: ${SECRET_KEY}
      #MEDIAWIKI_META_NAMESPACE: MyNamespace
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_DB_USER: wikiuser
      #MEDIAWIKI_DB_PREFIX: wiki_
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: ${DB_PASSWORD}
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_DEFAULT_SKIN: vector
      MEDIAWIKI_SMTP: 1
      MEDIAWIKI_SMTP_SSL_VERIFY_PEER: 0
      MEDIAWIKI_SMTP_HOST: ${SMTP_HOST}
      MEDIAWIKI_SMTP_IDHOST: ${SMTP_IDHOST}
      MEDIAWIKI_SMTP_PORT: 587
      MEDIAWIKI_SMTP_AUTH: 1
      MEDIAWIKI_SMTP_USERNAME: ${SMTP_USERNAME}
      MEDIAWIKI_SMTP_PASSWORD: ${SMTP_PASSWORD}
      MEDIAWIKI_EMERGENCY_CONTACT: ${EMERGENCY_CONTACT}
      MEDIAWIKI_PASSWORD_SENDER: ${PASSWORD_SENDER}
      MEDIAWIKI_DEBUG: 0
    ports:
    - "80:80"
    - "443:443"
    links:
    - db:db
    volumes:
    - /srv/mediawiki/images:/var/www/mediawiki/images
    - ./testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    - ./testdata/ssl/cert.crt:/etc/ssl/crt/cert.crt:ro
    - ./testdata/ssl/private.key:/etc/ssl/crt/private.key:ro
    - ./testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} # Debug
    volumes:
    - /srv/mediawiki/mysql:/var/lib/mysql
