version: '2'
services:
  wiki:
    #build: ./../../../ # Uncomment to build
    image: kristophjunge/mediawiki
    environment:
      MEDIAWIKI_SERVER: https://localhost
      MEDIAWIKI_SITENAME: MyWiki
      MEDIAWIKI_LANGUAGE_CODE: en
      MEDIAWIKI_SECRET_KEY: mysecret
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: mysecret
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_ENABLE_VISUAL_EDITOR: 1
      MEDIAWIKI_DEFAULT_SKIN: vector
    ports:
    - "8080:80"
    links:
    - db:db
    volumes:
    - /srv/mediawiki/images:/var/www/mediawiki/images
    #- ./../../../testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    #- ./../../../testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: wikidb
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: mysecret
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
    - /srv/mediawiki/mysql:/var/lib/mysql
