# Do not forget to create a new database on your first run:
# $ docker exec -it wiki /script/install.sh <username> <password>
version: '2'
services:
  wiki:
    #build: ./../../../ # Uncomment to build from source
    image: kristophjunge/mediawiki
    container_name: wiki
    environment:
      MEDIAWIKI_SERVER: http://localhost:8080
      MEDIAWIKI_SITENAME: MyWiki
      MEDIAWIKI_LANGUAGE_CODE: en
      MEDIAWIKI_SECRET_KEY: mysecret
      MEDIAWIKI_DB_TYPE: sqlite
      MEDIAWIKI_DB_NAME: wikidb
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_ENABLE_VISUAL_EDITOR: 0
      MEDIAWIKI_DEFAULT_SKIN: vector
    ports:
    - "8080:80"
    volumes:
    - /srv/mediawiki/images:/images
    - /srv/mediawiki/data:/data
    #- ./../../../testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    #- ./../../../testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
